name: Default

on:
  push:
    branches: [main]
    tags-ignore:
      - "*"
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ShellCheck
        run: |-
          shellcheck -x entrypoint.sh
